FROM node:20-alpine AS build-ui
WORKDIR /app

COPY short-url-admin-ui/package.json short-url-admin-ui/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY short-url-admin-ui .
RUN yarn build

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-ui /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
