-- ======================================================
-- Short URL 시스템 - Oracle DDL 및 인덱스 스크립트
-- 생성일: 2025-12-23
-- ======================================================

-- 1. 테이블 및 제약 조건 삭제 (초기화용 - 필요 시 주석 해제)
/*
DROP TABLE TBL_REDIRECTION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE TBL_SHORT_URL CASCADE CONSTRAINTS;
DROP TABLE TBL_CLIENT_ACCESS_KEY CASCADE CONSTRAINTS;
DROP TABLE TBL_USER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_CLIENT_ACCESS_KEY;
DROP SEQUENCE SEQ_SHORT_URL;
DROP SEQUENCE SEQ_REDIRECTION_HISTORY;
*/

-- ======================================================
-- 2. 테이블 생성 (Tables)
-- ======================================================

-- 2.1 사용자 및 고객사 테이블
CREATE TABLE TBL_USER (
    ID              NUMBER(19, 0)       NOT NULL,
    USERNAME        VARCHAR2(50)        NOT NULL,
    GROUP_NAME      VARCHAR2(100),
    API_KEY         VARCHAR2(255),
    REFRESH_TOKEN   VARCHAR2(255),
    IS_DEL          CHAR(1)             DEFAULT 'N' NOT NULL,
    CREATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UK_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CHK_USER_IS_DEL CHECK (IS_DEL IN ('Y', 'N'))
);

COMMENT ON TABLE TBL_USER IS '사용자 및 고객사 정보';
COMMENT ON COLUMN TBL_USER.ID IS 'PK';
COMMENT ON COLUMN TBL_USER.USERNAME IS '사용자 아이디 (고유 식별값)';
COMMENT ON COLUMN TBL_USER.GROUP_NAME IS '소속 그룹 또는 고객사 명칭';
COMMENT ON COLUMN TBL_USER.API_KEY IS 'API 호출 시 사용하는 인증 키';
COMMENT ON COLUMN TBL_USER.IS_DEL IS '삭제 여부 (Y/N)';

-- 2.2 클라이언트 접근 키 테이블
CREATE TABLE TBL_CLIENT_ACCESS_KEY (
    ID              NUMBER(19, 0)       NOT NULL,
    NAME            VARCHAR2(100)       NOT NULL,
    KEY_VALUE       VARCHAR2(255)       NOT NULL,
    ISSUED_BY       VARCHAR2(50),
    DESCRIPTION     VARCHAR2(1000),
    EXPIRES_AT      TIMESTAMP,
    LAST_USED_AT    TIMESTAMP,
    IS_ACTIVE       CHAR(1)             DEFAULT 'Y' NOT NULL,
    IS_DEL          CHAR(1)             DEFAULT 'N' NOT NULL,
    CREATED_AT      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CLIENT_ACCESS_KEY PRIMARY KEY (ID),
    CONSTRAINT UK_CAKEY_VALUE UNIQUE (KEY_VALUE),
    CONSTRAINT CHK_CAKEY_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_CAKEY_IS_DEL CHECK (IS_DEL IN ('Y', 'N'))
);

COMMENT ON TABLE TBL_CLIENT_ACCESS_KEY IS '비회원 기반 단축 URL 발급용 키';

-- 2.3 단축 URL 테이블
CREATE TABLE TBL_SHORT_URL (
    ID                    NUMBER(19, 0)       NOT NULL,
    LONG_URL              VARCHAR2(2048)      NOT NULL,
    SHORT_URL             VARCHAR2(20)        NOT NULL,
    USER_ID               NUMBER(19, 0),
    CLIENT_ACCESS_KEY_ID  NUMBER(19, 0),
    EXPIRED_AT            TIMESTAMP,
    BOT_TYPE              VARCHAR2(20),
    BOT_SERVICE_KEY       VARCHAR2(100),
    SURVEY_ID             VARCHAR2(50),
    SURVEY_VER            NUMBER(5, 0),
    IS_DEL                CHAR(1)             DEFAULT 'N' NOT NULL,
    CREATED_AT            TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SHORT_URL PRIMARY KEY (ID),
    CONSTRAINT UK_SHORT_URL_KEY UNIQUE (SHORT_URL),
    CONSTRAINT FK_SURL_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID),
    CONSTRAINT FK_SURL_CAKEY FOREIGN KEY (CLIENT_ACCESS_KEY_ID) REFERENCES TBL_CLIENT_ACCESS_KEY(ID),
    CONSTRAINT CHK_SURL_IS_DEL CHECK (IS_DEL IN ('Y', 'N'))
);

COMMENT ON TABLE TBL_SHORT_URL IS '단축 URL 매핑 정보';
COMMENT ON COLUMN TBL_SHORT_URL.LONG_URL IS '원본 URL';
COMMENT ON COLUMN TBL_SHORT_URL.SHORT_URL IS '생성된 단축 키 (Base62)';

-- 2.4 리다이렉션 이력 테이블
CREATE TABLE TBL_REDIRECTION_HISTORY (
    ID                NUMBER(19, 0)       NOT NULL,
    SHORT_URL_ID      NUMBER(19, 0)       NOT NULL,
    REFERER           VARCHAR2(2048),
    USER_AGENT        VARCHAR2(500),
    IP                VARCHAR2(50),
    DEVICE_TYPE       VARCHAR2(20),
    OS                VARCHAR2(50),
    BROWSER           VARCHAR2(50),
    COUNTRY           VARCHAR2(10),
    CITY              VARCHAR2(100),
    REDIRECT_AT       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
    BOT_TYPE          VARCHAR2(20),
    BOT_SERVICE_KEY   VARCHAR2(100),
    SURVEY_ID         VARCHAR2(50),
    SURVEY_VER        NUMBER(5, 0),
    CONSTRAINT PK_REDIRECTION_HISTORY PRIMARY KEY (ID),
    CONSTRAINT FK_RHIST_SURL FOREIGN KEY (SHORT_URL_ID) REFERENCES TBL_SHORT_URL(ID)
);

COMMENT ON TABLE TBL_REDIRECTION_HISTORY IS '단축 URL 접속 이력 (로그)';


-- ======================================================
-- 3. 시퀀스 생성 (Sequences)
-- ======================================================
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLIENT_ACCESS_KEY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SHORT_URL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REDIRECTION_HISTORY START WITH 1 INCREMENT BY 1;


-- ======================================================
-- 4. 인덱스 생성 (Indexes)
-- ======================================================

-- 4.1 리다이렉션 이력 통계용 결합 인덱스 (가장 중요)
-- 특정 URL의 기간별 접속 통계 산출 최적화
CREATE INDEX IDX_RHIST_SURL_DATE ON TBL_REDIRECTION_HISTORY (SHORT_URL_ID, REDIRECT_AT);

-- 4.2 전체 통계용 기간 인덱스
-- 전체 시스템 접속 추이 조회 최적화
CREATE INDEX IDX_RHIST_REDIRECT_AT ON TBL_REDIRECTION_HISTORY (REDIRECT_AT);

-- 4.3 단축 URL 최신순 조회용 인덱스
-- 관리자 UI 리스트 조회 시 정렬 성능 확보
CREATE INDEX IDX_SURL_CREATED_AT ON TBL_SHORT_URL (CREATED_AT DESC);

-- 4.4 외래 키 인덱스 (FK 성능 및 데드락 방지)
CREATE INDEX IDX_SURL_USER_ID ON TBL_SHORT_URL (USER_ID);
CREATE INDEX IDX_SURL_CAKEY_ID ON TBL_SHORT_URL (CLIENT_ACCESS_KEY_ID);
