# --- Development 환경 설정 ---
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: my_user
    password: ENC(UIcFmVIQOtGDRGD+zoC2eVvlzlSiB91fcNmLKTWkY7fKZyJjY87ryvMH4fvpfwO3)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate # 스키마가 올바른지 검증만 함
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

server:
  port: 8080

base-url: http://dev.your-domain.com/

short-url:
  redirect:
    public-url: http://dev.your-domain.com/r/